import { describe, it, expect } from 'vitest';
import { NoteUtils } from './NoteUtils';

describe('NoteUtils.validateContent', () => {
  it('rejects empty content', () => {
    expect(NoteUtils.validateContent('')).toEqual({
      isValid: false,
      reason: 'Note is empty',
    });
  });

  it('rejects whitespace-only content', () => {
    expect(NoteUtils.validateContent('   \n\n  ')).toEqual({
      isValid: false,
      reason: 'Note is empty',
    });
  });

  it('rejects content shorter than 50 characters', () => {
    const short = 'This is a short note.';
    expect(NoteUtils.validateContent(short)).toEqual({
      isValid: false,
      reason: 'Note is too short to summarize (minimum 50 characters)',
    });
  });

  it('accepts content with 50+ characters', () => {
    const long = 'A'.repeat(50);
    expect(NoteUtils.validateContent(long)).toEqual({ isValid: true });
  });

  it('rejects content that is only a summary block', () => {
    const summaryOnly = '# Summary\n\n## Generated by AI\n\n*Generated on 1/1/2025*\n\nSome summary text here.\n\n---\n\n';
    expect(NoteUtils.validateContent(summaryOnly).isValid).toBe(false);
  });
});

describe('NoteUtils.truncateForAI', () => {
  it('returns content unchanged if under the limit', () => {
    const content = 'Hello world';
    expect(NoteUtils.truncateForAI(content)).toBe(content);
  });

  it('truncates content exceeding the limit', () => {
    const content = 'A'.repeat(10000);
    const result = NoteUtils.truncateForAI(content, 8000);
    expect(result.length).toBeLessThanOrEqual(8000);
    expect(result).toContain('[Note: Content truncated for processing]');
  });

  it('accepts a custom max length', () => {
    const content = 'A'.repeat(500);
    const result = NoteUtils.truncateForAI(content, 200);
    expect(result.length).toBeLessThanOrEqual(200);
    expect(result).toContain('[Note: Content truncated for processing]');
  });
});

describe('NoteUtils.extractContentForSummary', () => {
  it('returns content unchanged when no summary exists', () => {
    const content = '# My Note\n\nSome content here.';
    expect(NoteUtils.extractContentForSummary(content)).toBe(content);
  });

  it('strips existing summary block from content', () => {
    const content = '# Summary\n\n*Generated on 1/1/2025*\n\nOld summary.\n\n---\n\n# My Note\n\nActual content.';
    const result = NoteUtils.extractContentForSummary(content);
    expect(result).not.toContain('# Summary');
    expect(result).not.toContain('Old summary');
    expect(result).toContain('Actual content');
  });

  it('collapses excessive whitespace', () => {
    const content = 'Line one.\n\n\n\n\nLine two.';
    const result = NoteUtils.extractContentForSummary(content);
    expect(result).toBe('Line one.\n\nLine two.');
  });
});

describe('NoteUtils.insertSummary', () => {
  it('adds summary at the beginning when no existing summary', () => {
    const content = '# My Note\n\nSome content here.';
    const summary = 'This is a test summary.';
    const result = NoteUtils.insertSummary(content, summary);
    expect(result).toMatch(/^# Summary\n/);
    expect(result).toContain(summary);
    expect(result).toContain('Some content here.');
  });

  it('replaces existing summary instead of duplicating', () => {
    const content = '# My Note\n\nSome content here.';
    const firstResult = NoteUtils.insertSummary(content, 'First summary.');
    const secondResult = NoteUtils.insertSummary(firstResult, 'Second summary.');

    // Should contain only one summary section
    const summaryCount = (secondResult.match(/# Summary/g) || []).length;
    expect(summaryCount).toBe(1);

    // Should contain the new summary, not the old one
    expect(secondResult).toContain('Second summary.');
    expect(secondResult).not.toContain('First summary.');

    // Should still contain the original content
    expect(secondResult).toContain('Some content here.');
  });

  it('includes a timestamp', () => {
    const content = 'Some long content here that is enough to summarize.';
    const result = NoteUtils.insertSummary(content, 'A summary.');
    expect(result).toMatch(/Generated on .+/);
  });

  it('preserves original content after the summary', () => {
    const content = '# Heading One\n\nParagraph.\n\n# Heading Two\n\nMore content.';
    const result = NoteUtils.insertSummary(content, 'A summary.');
    expect(result).toContain('# Heading One');
    expect(result).toContain('Paragraph.');
    expect(result).toContain('# Heading Two');
    expect(result).toContain('More content.');
  });
});
